name: CI CD pipeline unit tests

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
	
	  - name: Login to Docker Hub
	    uses: docker/login-action@v3
		with:
		  username: ${{ vars.DOCKER_USERNAME }}
		  password: ${{ secrets.DOCKERHUB_TOKEN }}
 
	  -
	    name: Set up Docker Buildx
		uses: docker/setup-buildx-action@v3
		
	  - name: Build and test
	    uses: docker/build-push-action@v6
		with:
		  target: build
		  load: true
		  
	  -
	    name: Build and push
		uses: docker/build-push-action@v6
		with:
		  platforms: linux/amd64, linux/amd64
		  push: true,
		  target: final
		  tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
		  
  build:
	    name: Build and test
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        
      - name: Run tests
        run: dotnet test
