name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      if: github.ref == 'refs/heads/master'
      run: |
        docker build -t andnik98/vacancy:latest -f ./WebApi/Dockerfile .

    - name: Push Docker image
      if: github.ref == 'refs/heads/master'
      run: |
        docker push andnik98/vacancy:latest
