name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Authenticate to GitHub Package Registry
      run: nuget sources add -name "Yuman-net" -source "https://nuget.pkg.github.com/Yuman-net/index.json" -user "and.nik.dev@gmail.com" -password "${{ secrets.PKG_SECRET }}"


    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PKG_SECRET }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./WebApi/Dockerfile
        push: true
        tags: ghcr.io/yuman-net/vacancyservice:latest
