name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: TOKEN
      run: echo "${{ secrets.PKG_SECRET }}"
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Configure NuGet
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/Yuman-net/index.json --name GitHub --username and.nik.dev@gmail.com --password ${{ secrets.PKG_SECRET }} --store-password-in-clear-text
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release ##--no-restore
      ##env:
        ##  NuGetPackageSourceCredentials_GitHub: Username=and.nik.dev@gmail.com;Password="${{ secrets.PKG_SECRET }}"

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PKG_SECRET }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./WebApi/Dockerfile
        push: true
        tags: ghcr.io/yuman-net/vacancyservice:latest
        build-arg: |
          NUGET_PASS=${{ secrets.PKG_SECRET }}
          STRING111=RESULT111
